SELECT
    D.DEPTCODE,
    D.DEPTNAME,
    SUM(E.SALARY) AS TOTALSALARY,
    D.TOTALEMP
FROM
    EMPLOYEE   E
    INNER JOIN DEPARTMENT D
    ON D.DEPTCODE = E.DEPTCODE
WHERE
    E.WORKSTATUS = 'W'
    AND D.TOTALEMP < 5
GROUP BY
    D.DEPTCODE, D.DEPTNAME, D.TOTALEMP
HAVING
    SUM(E.SALARY) > 100000
ORDER BY
    D.DEPTCODE DESC, TOTALSALARY DESC;