SELECT
    P.SPVCODE,
    P.SPVTNAME,
    D.DEPTCODE,
    D.DEPTNAME,
    E.EMPNO,
    E.FNAME,
    E.LNAME,
FROM
    EMPLOYEE E
    INNER JOIN DEPARTMENT D
    ON E.DEPTCODE = D.DEPTCODE
    INNER JOIN SUPERVISOR P
    ON D.DEPTCODE = P.DEPTCODE
WHERE
    E.WORKSTATUS = 'W'
ORDER BY
    P.SPVCODE, E.DEPTCODE, E.EMPNO