SELECT
    MIN(E.DEPTCODE),
    COUNT(*),
    AVG(E.SALARY)
FROM
    EMPLOYEE E
WHERE
    E.WORKSTATUS = 'W'
    AND SALARY >15000
GROUP BY
    E.DEPTCODE
HAVING
    AVG(E.SALARY) BETWEEN 20000 AND 45000
ORDER BY
    E.DEPTCODE DESC