SELECT
    *
FROM
    SETPROVINCE
    LEFT OUTER JOIN EMPLOYEE
    ON EMPLOYEE.SPVCODE = SETPROVINCE.SPVCODE
    AND WORKSTATUS = 'W'
    INNER JOIN DEPARTMENT
    ON EMPLOYEE.DEPTCODE = DEPARTMENT.DEPTCODE
ORDER BY
    SETPROVINCE.SPVCODE,
    EMPLOYEE.DEPTCODE,
    EMPNO